// <auto-generated />
namespace Progeaiiit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Position_inscription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Position_inscription));
        
        string IMigrationMetadata.Id
        {
            get { return "201903051421182_Position_inscription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
