// <auto-generated />
namespace Progeaiiit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test41 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test41));
        
        string IMigrationMetadata.Id
        {
            get { return "201903041011385_test41"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
