// <auto-generated />
namespace Progeaiiit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class race_optionnel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(race_optionnel));
        
        string IMigrationMetadata.Id
        {
            get { return "201903060852504_race_optionnel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
